# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
install:
  ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap
# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

  - R_VERSION: patched

  - R_VERSION: oldrel
    RTOOLS_VERSION: 32
    CRAN: http://cran.rstudio.com

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - krlmlr+appveyor@mailbox.org
   subject: 'r-appveyor build {{status}}'                  # optional
   message: "https://ci.appveyor.com/project/krlmlr/r-appveyor"    # optional
   on_build_success: false
   on_build_failure: true
   on_build_status_changed: true
