#' @rdname Geom
#' @format NULL
#' @usage NULL
#' @export
GeomHex <- ggproto("GeomHex", Geom,
  draw_group = function(self, data, panel_params, coord, lineend = "butt",
                        linejoin = "mitre", linemitre = 10) {
    if (empty(data)) {
      return(zeroGrob())
    }
    data <- fix_linewidth(data, snake_class(self))

    # Get hex sizes
    if (!is.null(data$width)) {
      dx <- data$width[1] / 2
    } else {
      dx <- resolution(data$x, FALSE, TRUE)
    }
    # Adjust for difference in width and height of regular hexagon. 1.15 adjusts
    # for the effect of the overlapping range in y-direction on the resolution
    # calculation
    if (!is.null(data$height)) {
      dy <- data$height[1] /  sqrt(3) / 2
    } else {
      dy <- resolution(data$y, FALSE, TRUE) / sqrt(3) / 2 * 1.15
    }

    n <- nrow(data)
    hexC <- hexbin::hexcoords(dx, dy, n = n)

    columns <- intersect(c("x", "y", "radius"), names(data))
    hexdata <- vec_rep_each(data[columns], times = 6L)
    hexdata$radius <- hexdata$radius %||% 1
    hexdata$x <- hexC$x * hexdata$radius + hexdata$x
    hexdata$y <- hexC$y * hexdata$radius + hexdata$y

    coords <- coord$transform(hexdata, panel_params)

    ggname("geom_hex", polygonGrob(
      coords$x, coords$y,
      gp = gg_par(
        col = data$colour,
        fill = fill_alpha(data$fill, data$alpha),
        lwd = data$linewidth,
        lty = data$linetype,
        lineend = lineend,
        linejoin = linejoin,
        linemitre = linemitre
      ),
      default.units = "native",
      id.lengths = rep.int(6, n)
    ))
  },

  required_aes = c("x", "y"),

  default_aes = aes(
    colour = from_theme(colour %||% NA),
    fill = from_theme(fill %||% col_mix(ink, paper)),
    linewidth = from_theme(borderwidth),
    linetype = from_theme(bordertype),
    radius = 1,
    alpha = NA
  ),

  draw_key = draw_key_polygon,

  rename_size = TRUE
)

#' Hexagonal heatmap of 2d bin counts
#'
#' Divides the plane into regular hexagons, counts the number of cases in
#' each hexagon, and then (by default) maps the number of cases to the hexagon
#' fill.  Hexagon bins avoid the visual artefacts sometimes generated by
#' the very regular alignment of [geom_bin_2d()].
#'
#' @aesthetics GeomHex
#' @aesthetics StatBinhex
#' @seealso [stat_bin_2d()] for rectangular binning
#' @param geom,stat Override the default connection between `geom_hex()` and
#'   `stat_bin_hex()`. For more information about overriding these connections,
#'   see how the [stat][layer_stats] and [geom][layer_geoms] arguments work.
#' @export
#' @inheritParams shared_layer_parameters
#' @export
#' @examples
#' d <- ggplot(diamonds, aes(carat, price))
#' d + geom_hex()
#'
#' \donttest{
#' # You can control the size of the bins by specifying the number of
#' # bins in each direction:
#' d + geom_hex(bins = 10)
#' d + geom_hex(bins = 30)
#'
#' # Or by specifying the width of the bins
#' d + geom_hex(binwidth = c(1, 1000))
#' d + geom_hex(binwidth = c(.1, 500))
#'
#' # The hexagons can be scaled by tuning the radius aesthetic
#' d + geom_hex(aes(radius = after_stat(ncount)))
#' }
geom_hex <- make_constructor(GeomHex, stat = 'binhex')
