
#' Generate expansion vector for scales
#'
#' This is a convenience function for generating scale expansion vectors
#' for the `expand` argument of [scale_(x|y)_continuous][scale_x_continuous()]
#' and [scale_(x|y)_discrete][scale_x_discrete()]. The expansions vectors are used to
#' add some space between the data and the axes.
#'
#' @param mult vector of multiplicative range expansion factors.
#'   If length 1, both the lower and upper limits of the scale
#'   are expanded outwards by `mult`. If length 2, the lower limit
#'   is expanded by `mult[1]` and the upper limit by `mult[2]`.
#' @param add vector of additive range expansion constants.
#'   If length 1, both the lower and upper limits of the scale
#'   are expanded outwards by `add` units. If length 2, the
#'   lower limit is expanded by `add[1]` and the upper
#'   limit by `add[2]`.
#'
#' @export
#' @examples
#' # No space below the bars but 10% above them
#' ggplot(mtcars) +
#'   geom_bar(aes(x = factor(cyl))) +
#'   scale_y_continuous(expand = expand_scale(mult = c(0, .1)))
#'
#' # Add 2 units of space on the left and right of the data
#' ggplot(subset(diamonds, carat > 2), aes(cut, clarity)) +
#'   geom_jitter() +
#'   scale_x_discrete(expand = expand_scale(add = 2))
#'
#' # Reproduce the default range expansion used
#' # when the 'expand' argument is not specified
#' ggplot(subset(diamonds, carat > 2), aes(cut, price)) +
#'   geom_jitter() +
#'   scale_x_discrete(expand = expand_scale(add = .6)) +
#'   scale_y_continuous(expand = expand_scale(mult = .05))
#'
expand_scale = function(mult = 0, add = 0) {
  stopifnot(is.numeric(mult) && is.numeric(add))
  stopifnot((length(mult) %in% 1:2) && (length(add) %in% 1:2))

  mult <- rep(mult, length.out = 2)
  add <- rep(add, length.out = 2)
  c(mult[1], add[1], mult[2], add[2])
}

#' Expand a numeric range
#'
#' @param limits A numeric vector of length 2 giving the
#'   range to expand.
#' @param expand A numeric vector of length 2 (`c(add, mult)`)
#'   or length 4 (`c(mult_left, add_left, mult_right, add_right)`),
#'   as generated by [expand_scale()].
#'
#' @return The expanded `limits`
#'
expand_range4 <- function(limits, expand) {
  stopifnot(
    is.numeric(expand),
    length(expand) %in% c(2,4)
  )

  # If only two expansion constants are given (i.e. the old syntax),
  # reuse them to generate a four-element expansion vector
  if (length(expand) == 2) {
    expand <- c(expand, expand)
  }

  # Calculate separate range expansion for the lower and
  # upper range limits, and then combine them into one vector
  lower <- expand_range(limits, expand[1], expand[2])[1]
  upper <- expand_range(limits, expand[3], expand[4])[2]
  c(lower, upper)
}

#' Calculate the final scale dimension
#'
#' @param scale A position scale (e.g., [scale_x_continuous()] or [scale_x_discrete()])
#' @param scale_limits The scale-supplied limits, in transformed data space
#' @param coord_limits The user-supplied limits, in untransformed data space
#'   (or `NULL` for no user-supplied limits). `NA` values will fall back to the
#'   scale limits.
#' @param expansion The length-4 expansion to use, calculated by [expand_scale()]
#'   or [expand_default()].
#' @param coord_trans A transformation defining the space where
#'   expansion should take place.
#'
#' @return The (possibly expanded) scale limits, in scale-transformed data space
#' @noRd
#'
scale_dimension <- function(scale, coord_limits = NULL,
                            expansion = expand_scale(0, 0),
                            coord_trans = identity_trans()) {

  coord_limits <- coord_limits %||% c(NA_real_, NA_real_)

  # transform coord limits to transformed scale data space
  coord_limits_scale <- scale$trans$transform(coord_limits)

  # replace scale limits with non-NA coord limits
  scale_limits <- ifelse(is.na(coord_limits_scale), scale$dimension(), coord_limits_scale)

  # expand limits in coordinate space
  coord_limits <- coord_trans$transform(scale_limits)
  coord_limits <- expand_range4(coord_limits, expansion)
  final_scale_limits <- coord_trans$inverse(coord_limits)

  # if any non-finite values were introduced in the transformations,
  # replace them with the original scale limits
  ifelse(is.finite(final_scale_limits), final_scale_limits, scale_limits)
}

#' Calculate the default expansion for a scale
#'
#' @param scale A position scale (e.g., [scale_x_continuous()] or [scale_x_discrete()])
#' @param discrete,continuous Default scale expansion factors for
#'   discrete and continuous scales, respectively.
#' @param expand Should any expansion be applied?
#'
#' @return One of `discrete`, `continuous`, or `scale$expand`
#' @noRd
#'
expand_default <- function(scale, discrete = expand_scale(add = 0.6),
                           continuous = expand_scale(mult = 0.05), expand = TRUE) {
  if (!expand) {
    return(expand_scale(0, 0))
  }

  scale$expand %|W|% if (scale$is_discrete()) discrete else continuous
}
