
#' Generate expansion vector for scales
#'
#' This is a convenience function for generating scale expansion vectors
#' for the `expand` argument of [scale_(x|y)_continuous][scale_x_continuous()]
#' and [scale_(x|y)_discrete][scale_x_discrete()]. The expansions vectors are used to
#' add some space between the data and the axes.
#'
#' @param mult vector of multiplicative range expansion factors.
#'   If length 1, both the lower and upper limits of the scale
#'   are expanded outwards by `mult`. If length 2, the lower limit
#'   is expanded by `mult[1]` and the upper limit by `mult[2]`.
#' @param add vector of additive range expansion constants.
#'   If length 1, both the lower and upper limits of the scale
#'   are expanded outwards by `add` units. If length 2, the
#'   lower limit is expanded by `add[1]` and the upper
#'   limit by `add[2]`.
#'
#' @export
#' @examples
#' # No space below the bars but 10% above them
#' ggplot(mtcars) +
#'   geom_bar(aes(x = factor(cyl))) +
#'   scale_y_continuous(expand = expand_scale(mult = c(0, .1)))
#'
#' # Add 2 units of space on the left and right of the data
#' ggplot(subset(diamonds, carat > 2), aes(cut, clarity)) +
#'   geom_jitter() +
#'   scale_x_discrete(expand = expand_scale(add = 2))
#'
#' # Reproduce the default range expansion used
#' # when the 'expand' argument is not specified
#' ggplot(subset(diamonds, carat > 2), aes(cut, price)) +
#'   geom_jitter() +
#'   scale_x_discrete(expand = expand_scale(add = .6)) +
#'   scale_y_continuous(expand = expand_scale(mult = .05))
#'
expand_scale = function(mult = 0, add = 0) {
  stopifnot(is.numeric(mult) && is.numeric(add))
  stopifnot((length(mult) %in% 1:2) && (length(add) %in% 1:2))

  mult <- rep(mult, length.out = 2)
  add <- rep(add, length.out = 2)
  c(mult[1], add[1], mult[2], add[2])
}


#' Calculate limits for continuous scales
#'
#' @param limits a numeric vector of length 2 or a function that will be
#'   called on `default_limits` that returns a numeric vector of length 2.
#'   The `limits` are in transformed data space.
#' @param default_limits a numeric vector of length 2 to be used as a
#'   fallback for `NA` limits. This is usually the minimum and maximum
#'   value observed in the transformed data.
#' @param trans The transform (see [scales::trans_new()]) that was used
#'   to calculate `limits` and `default_limits`.
#'
#' @noRd
#'
calculate_limits <- function(limits = c(NA_real_, NA_real_),
                             default_limits = c(NA_real_, NA_real_),
                             trans = identity_trans()) {

  if (!is.numeric(default_limits) || (length(default_limits) != 2)) {
    stop("`default_limits` must be a numeric vector of length 2")
  }

  if (is.function(limits)) {
    # if limits is a function, it expects to work in trans$inverse() space
    limits <- trans$transform(limits(trans$inverse(default_limits)))
  }

  if (!is.numeric(limits) || (length(limits) != 2)) {
    stop(
      "`limits` must be a numeric vector of length 2 or a function of `default_limits` ",
      "that returns a numeric vector of length 2.",
      call. = FALSE
    )
  }

  # replace NA limits with corresponding value in default_limits
  ifelse(is.na(limits), default_limits, limits)
}

#' Expand a numeric range
#'
#' @param limits A numeric vector of length 2 giving the
#'   range to expand.
#' @param expand A numeric vector of length 2 (`c(add, mult)`)
#'   or length 4 (`c(mult_left, add_left, mult_right, add_right)`),
#'   as generated by [expand_scale()].
#'
#' @return The expanded `limits`
#'
expand_range4 <- function(limits, expand) {
  stopifnot(
    is.numeric(expand),
    length(expand) %in% c(2,4)
  )

  # If only two expansion constants are given (i.e. the old syntax),
  # reuse them to generate a four-element expansion vector
  if (length(expand) == 2) {
    expand <- c(expand, expand)
  }

  # Calculate separate range expansion for the lower and
  # upper range limits, and then combine them into one vector
  lower <- expand_range(limits, expand[1], expand[2])[1]
  upper <- expand_range(limits, expand[3], expand[4])[2]
  c(lower, upper)
}


#' Calculate the final range
#'
#' @param scale A position scale (e.g., [scale_x_continuous()] or [scale_x_discrete()])
#' @param limits The user-supplied limits, in untransformed data space
#' @param expand `TRUE` of the final limits should be expanded, `FALSE` otherwise
#'
#' @return The (possibly expanded) `limits`
#' @noRd
#'
scale_range <- function(scale, limits = NULL, expand = TRUE) {
  expansion <- if (expand) expand_default(scale) else expand_scale(0, 0)

  if (is.null(limits)) {
    scale$dimension(expansion)
  } else {
    continuous_range <- range(scale$transform(limits))
    expand_range4(continuous_range, expansion)
  }
}



expand_default <- function(scale, discrete = c(0, 0.6, 0, 0.6), continuous = c(0.05, 0, 0.05, 0)) {
  if (!is.waive(scale$expand)) {
    return(scale$expand)
  }

  if (scale$is_discrete()) discrete else continuous
}
